USE [grocery_app_db]
GO
SET IDENTITY_INSERT [dbo].[ProductCategories] ON 

INSERT [dbo].[ProductCategories] ([CategoryId], [Category], [SubCategory]) VALUES (1, N'grocery', N'fruits')
INSERT [dbo].[ProductCategories] ([CategoryId], [Category], [SubCategory]) VALUES (2, N'vendor', N'vegetables')

SET IDENTITY_INSERT [dbo].[ProductCategories] OFF
GO
SET IDENTITY_INSERT [dbo].[Offers] ON 

INSERT [dbo].[Offers] ([OfferId], [Title], [Discount]) VALUES (1, N'd', 25)

SET IDENTITY_INSERT [dbo].[Offers] OFF
GO
SET IDENTITY_INSERT [dbo].[Products] ON 


INSERT [dbo].[Products] ([ProductId], [Title], [Description], [CategoryId], [OfferId], [Price], [Quantity], [ImageName]) VALUES (6, N'Fresh Apples', N'Fruits and vegetables offer a vibrant spectrum of colors each indicating a unique blend of essential nutrients and antioxidants.A diet rich in fruits and vegetables is linked to lower risks of chronic diseases thanks to their fiber vitamins and minerals.From crunchy apples to juicy tomatoes the diverse textures and flavors of fruits and vegetables make for a delightful culinary experience.Incorporating a variety of fruits and vegetables in your meals promotes digestive health and supports a strong immune system.Whether you are savoring a sweet mango or enjoying a leafy green salad the natural goodness of fruits and vegetables contributes to your overall well-being.', 1, 1, 200, 245, N'')
INSERT [dbo].[Products] ([ProductId], [Title], [Description], [CategoryId], [OfferId], [Price], [Quantity], [ImageName]) VALUES (7, N'Fresh Bananas', N'Fruits and vegetables offer a vibrant spectrum of colors each indicating a unique blend of essential nutrients and antioxidants.A diet rich in fruits and vegetables is linked to lower risks of chronic diseases thanks to their fiber vitamins and minerals.From crunchy apples to juicy tomatoes the diverse textures and flavors of fruits and vegetables make for a delightful culinary experience.Incorporating a variety of fruits and vegetables in your meals promotes digestive health and supports a strong immune system.Whether you are savoring a sweet mango or enjoying a leafy green salad the natural goodness of fruits and vegetables contributes to your overall well-being.', 1, 1, 100, 1000, N'')
INSERT [dbo].[Products] ([ProductId], [Title], [Description], [CategoryId], [OfferId], [Price], [Quantity], [ImageName]) VALUES (8, N'Fresh Mangoes', N'Fruits and vegetables offer a vibrant spectrum of colors each indicating a unique blend of essential nutrients and antioxidants.A diet rich in fruits and vegetables is linked to lower risks of chronic diseases thanks to their fiber vitamins and minerals.From crunchy apples to juicy tomatoes the diverse textures and flavors of fruits and vegetables make for a delightful culinary experience.Incorporating a variety of fruits and vegetables in your meals promotes digestive health and supports a strong immune system.Whether you are savoring a sweet mango or enjoying a leafy green salad the natural goodness of fruits and vegetables contributes to your overall well-being.', 1, 1, 120, 344, N'')
INSERT [dbo].[Products] ([ProductId], [Title], [Description], [CategoryId], [OfferId], [Price], [Quantity], [ImageName]) VALUES (9, N'Fresh PineApples', N'Fruits and vegetables offer a vibrant spectrum of colors each indicating a unique blend of essential nutrients and antioxidants.A diet rich in fruits and vegetables is linked to lower risks of chronic diseases thanks to their fiber vitamins and minerals.From crunchy apples to juicy tomatoes the diverse textures and flavors of fruits and vegetables make for a delightful culinary experience.Incorporating a variety of fruits and vegetables in your meals promotes digestive health and supports a strong immune system.Whether you are savoring a sweet mango or enjoying a leafy green salad the natural goodness of fruits and vegetables contributes to your overall well-being.', 1, 1, 180, 1200, N'')
INSERT [dbo].[Products] ([ProductId], [Title], [Description], [CategoryId], [OfferId], [Price], [Quantity], [ImageName]) VALUES (10, N'Fresh Grapes', N'Fruits and vegetables offer a vibrant spectrum of colors each indicating a unique blend of essential nutrients and antioxidants.A diet rich in fruits and vegetables is linked to lower risks of chronic diseases thanks to their fiber vitamins and minerals.From crunchy apples to juicy tomatoes the diverse textures and flavors of fruits and vegetables make for a delightful culinary experience.Incorporating a variety of fruits and vegetables in your meals promotes digestive health and supports a strong immune system.Whether you are savoring a sweet mango or enjoying a leafy green salad the natural goodness of fruits and vegetables contributes to your overall well-being.', 1, 1, 136, 250, N'')
INSERT [dbo].[Products] ([ProductId], [Title], [Description], [CategoryId], [OfferId], [Price], [Quantity], [ImageName]) VALUES (11, N'Fresh Potatoes', N'Fruits and vegetables offer a vibrant spectrum of colors each indicating a unique blend of essential nutrients and antioxidants.A diet rich in fruits and vegetables is linked to lower risks of chronic diseases thanks to their fiber vitamins and minerals.From crunchy apples to juicy tomatoes the diverse textures and flavors of fruits and vegetables make for a delightful culinary experience.Incorporating a variety of fruits and vegetables in your meals promotes digestive health and supports a strong immune system.Whether you are savoring a sweet mango or enjoying a leafy green salad the natural goodness of fruits and vegetables contributes to your overall well-being.', 2, 1, 110, 200, N'')
INSERT [dbo].[Products] ([ProductId], [Title], [Description], [CategoryId], [OfferId], [Price], [Quantity], [ImageName]) VALUES (12, N'Fresh Cauliflowers', N'Fruits and vegetables offer a vibrant spectrum of colors each indicating a unique blend of essential nutrients and antioxidants.A diet rich in fruits and vegetables is linked to lower risks of chronic diseases thanks to their fiber vitamins and minerals.From crunchy apples to juicy tomatoes the diverse textures and flavors of fruits and vegetables make for a delightful culinary experience.Incorporating a variety of fruits and vegetables in your meals promotes digestive health and supports a strong immune system.Whether you are savoring a sweet mango or enjoying a leafy green salad the natural goodness of fruits and vegetables contributes to your overall well-being.', 2, 1, 170, 178, N'')
INSERT [dbo].[Products] ([ProductId], [Title], [Description], [CategoryId], [OfferId], [Price], [Quantity], [ImageName]) VALUES (13, N'Fresh Spinach', N'Fruits and vegetables offer a vibrant spectrum of colors each indicating a unique blend of essential nutrients and antioxidants.A diet rich in fruits and vegetables is linked to lower risks of chronic diseases thanks to their fiber vitamins and minerals.From crunchy apples to juicy tomatoes the diverse textures and flavors of fruits and vegetables make for a delightful culinary experience.Incorporating a variety of fruits and vegetables in your meals promotes digestive health and supports a strong immune system.Whether you are savoring a sweet mango or enjoying a leafy green salad the natural goodness of fruits and vegetables contributes to your overall well-being.', 2, 1, 120, 350, N'')
INSERT [dbo].[Products] ([ProductId], [Title], [Description], [CategoryId], [OfferId], [Price], [Quantity], [ImageName]) VALUES (14, N'Fresh Brinjal', N'Fruits and vegetables offer a vibrant spectrum of colors each indicating a unique blend of essential nutrients and antioxidants.A diet rich in fruits and vegetables is linked to lower risks of chronic diseases thanks to their fiber vitamins and minerals.From crunchy apples to juicy tomatoes the diverse textures and flavors of fruits and vegetables make for a delightful culinary experience.Incorporating a variety of fruits and vegetables in your meals promotes digestive health and supports a strong immune system.Whether you are savoring a sweet mango or enjoying a leafy green salad the natural goodness of fruits and vegetables contributes to your overall well-being.', 2, 1, 40, 120, N'')
INSERT [dbo].[Products] ([ProductId], [Title], [Description], [CategoryId], [OfferId], [Price], [Quantity], [ImageName]) VALUES (15, N'Fresh Tomatoes', N'Fruits and vegetables offer a vibrant spectrum of colors each indicating a unique blend of essential nutrients and antioxidants.A diet rich in fruits and vegetables is linked to lower risks of chronic diseases thanks to their fiber vitamins and minerals.From crunchy apples to juicy tomatoes the diverse textures and flavors of fruits and vegetables make for a delightful culinary experience.Incorporating a variety of fruits and vegetables in your meals promotes digestive health and supports a strong immune system.Whether you are savoring a sweet mango or enjoying a leafy green salad the natural goodness of fruits and vegetables contributes to your overall well-being.', 2, 1, 179, 400, N'')


SET IDENTITY_INSERT [dbo].[Products] OFF
GO
SET IDENTITY_INSERT [dbo].[PaymentMethods] ON 

INSERT [dbo].[PaymentMethods] ([PaymentMethodId], [Type], [Provider], [Available], [Reason]) VALUES (1, N'Cash', N'', N'True', N'')

SET IDENTITY_INSERT [dbo].[PaymentMethods] OFF
GO